# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / VirtualBox
nav:
- Home: index.md
#- Overview: overview.md
- Install VirtualBox:
  - Windows 10 Host:
    - 'Main Install': install-host/win/install-win-host.md
    - 'Extension Pack': install-host/win/install-win-host-extension-pack.md
- 'Create Guests on Windows 10':
    - 'Linux Debian Jessie VM':  create-guest/linux-debian-jessie/create-guest-debian-jessie.md
- 'Create Images on Windows 10':
    - 'Linux Debian Jessie VM':  create-image/linux-debian-jessie/create-image-debian-jessie.md
- 'Install Images on Windows 10':
    - 'Linux Debian Jessie VM':  install-image/linux-debian-jessie/install-image-debian-jessie.md
- Troubleshooting: troubleshooting/troubleshooting.md
- Resources: resources/resources.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  Copyright 2019, Open Water Foundation
# ------------------------------------------------
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
google_analytics:
 - 'UA-135465513-1'
 - auto
# ------------------------------------------------
# Favicon is supposed to automatically be found:
# - in docs/img/favicon.ico
# - is a copy of docs/images/OWF-Logo-Favicon-32x32.ico
# - instead, with Material them, have a different approach (see "theme" below)
# ------------------------------------------------
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-virtualbox
# ------------------------------------------------
site_author:  Open Water Foundation
site_description:  Open Water Foundation Learn VirtualBox
# ------------------------------------------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  favicon: 'images/OWF-Logo-Favicon-32x32.ico'
# ------------------------------------------------
# The following controls how URLs are created
# - As of MkDocs 1.0 the default is true meaning URLs to a page ABC is ABC/ rather than something/ABC.html.
# - see:  https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
# use_directory_urls: true
# ------------------------------------------------
